import React, { useState, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';
import { Sparkles, AlertCircle, Loader2 } from 'lucide-react';

export default function GraphifyInsights() {
  const [reportMarkdown, setReportMarkdown] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await fetch('/api/graphify?type=report');
        if (res.ok) {
          const text = await res.text();
          setReportMarkdown(text);
        } else {
          setReportMarkdown('# Error loading report\\nPlease check if Graphify has run successfully.');
        }
      } catch (err) {
        setReportMarkdown('# Error\\nCould not reach the Graphify API.');
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, []);

  if (loading) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-zinc-500">
        <Loader2 className="animate-spin mb-4" size={32} />
        <p>Loading AI Insights...</p>
      </div>
    );
  }

  return (
    <div className="h-full flex flex-col bg-[#0a0a0c] border border-[var(--border-color)] rounded-xl overflow-hidden shadow-2xl">
      <div className="p-4 border-b border-[var(--border-color)] bg-[#0d0d11] flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles className="text-indigo-400" size={18} />
          <h2 className="text-sm font-bold text-white tracking-tight">AI Graphify Insights</h2>
        </div>
        <div className="text-[10px] text-zinc-500 uppercase font-semibold flex items-center gap-1">
          <AlertCircle size={12} /> Auto-generated by Claude
        </div>
      </div>
      <div className="flex-1 overflow-y-auto p-6 custom-scrollbar prose prose-invert max-w-none prose-h2:text-indigo-300 prose-h3:text-indigo-200 prose-a:text-indigo-400 hover:prose-a:text-indigo-300 prose-code:text-emerald-300 prose-code:bg-emerald-950/30 prose-code:px-1 prose-code:rounded">
        <ReactMarkdown>{reportMarkdown}</ReactMarkdown>
      </div>
    </div>
  );
}
