import React, { useState, useEffect } from 'react';
import { Database, FileCode2, Link as LinkIcon, Activity, HardDrive, Layers, Server, Layout } from 'lucide-react';

export default function OverviewDashboard() {
  const [stats, setStats] = useState(null);
  const [files, setFiles] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchOverview = async () => {
      try {
        const [statusRes, filesRes] = await Promise.all([
          fetch('/api/codegraph', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'status' }) }),
          fetch('/api/codegraph', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'files' }) })
        ]);
        
        const statusData = await statusRes.json();
        const filesData = await filesRes.json();
        
        setStats(statusData);
        setFiles(filesData);
      } catch (err) {
        console.error('Failed to load overview', err);
      } finally {
        setLoading(false);
      }
    };
    fetchOverview();
  }, []);

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center text-[var(--text-muted)] animate-pulse">
        <Activity className="w-5 h-5 mr-2" />
        <span className="text-xs font-mono">Analyzing System Architecture...</span>
      </div>
    );
  }

  // Calculate domains
  const domains = {
    Frontend: files.filter(f => f.path.startsWith('src/app') || f.path.includes('components')).length,
    Backend: files.filter(f => f.path.startsWith('src/app/api') || f.path.startsWith('src/infrastructure')).length,
    Agents: files.filter(f => f.path.startsWith('src/features/jobs/agents')).length,
    Config: files.filter(f => f.path.endsWith('.json') || f.path.endsWith('.yml') || f.path.endsWith('config.js')).length,
  };

  const totalDomainFiles = Object.values(domains).reduce((a, b) => a + b, 0);

  return (
    <div className="p-6 h-full overflow-y-auto custom-scrollbar space-y-8">
      <div>
        <h1 className="text-2xl font-semibold text-white tracking-tight mb-2">Architecture Overview</h1>
        <p className="text-[var(--text-secondary)] text-sm">Real-time system health and structural metrics generated by CodeGraph.</p>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-4 gap-4">
        <MetricCard icon={<FileCode2 />} label="Indexed Files" value={stats?.fileCount?.toLocaleString() || 0} />
        <MetricCard icon={<Database />} label="Graph Nodes" value={stats?.nodeCount?.toLocaleString() || 0} />
        <MetricCard icon={<LinkIcon />} label="Dependencies (Edges)" value={stats?.edgeCount?.toLocaleString() || 0} />
        <MetricCard icon={<HardDrive />} label="DB Size" value={`${((stats?.dbSizeBytes || 0) / 1024 / 1024).toFixed(2)} MB`} />
      </div>

      {/* Architecture Layers */}
      <div className="grid grid-cols-2 gap-6">
        <div className="bg-[var(--bg-elevated)] border border-[var(--border-color)] rounded-xl p-5">
          <h3 className="text-sm font-semibold text-white flex items-center gap-2 mb-4">
            <Layers className="w-4 h-4 text-indigo-400" />
            System Domains
          </h3>
          <div className="space-y-4">
            <DomainBar label="Frontend (React/UI)" count={domains.Frontend} total={totalDomainFiles} color="bg-blue-500" />
            <DomainBar label="Backend (API/Services)" count={domains.Backend} total={totalDomainFiles} color="bg-emerald-500" />
            <DomainBar label="AI Agents" count={domains.Agents} total={totalDomainFiles} color="bg-purple-500" />
            <DomainBar label="Configuration" count={domains.Config} total={totalDomainFiles} color="bg-zinc-500" />
          </div>
        </div>

        <div className="bg-[var(--bg-elevated)] border border-[var(--border-color)] rounded-xl p-5">
          <h3 className="text-sm font-semibold text-white flex items-center gap-2 mb-4">
            <Server className="w-4 h-4 text-amber-400" />
            Symbol Distribution
          </h3>
          {stats?.nodesByKind && (
            <div className="space-y-3">
              {Object.entries(stats.nodesByKind)
                .sort((a, b) => b[1] - a[1])
                .slice(0, 5)
                .map(([kind, count]) => (
                  <div key={kind} className="flex justify-between items-center text-xs">
                    <span className="text-[var(--text-secondary)] capitalize">{kind}</span>
                    <span className="font-mono text-[var(--text-base)] bg-[var(--bg-base)] px-2 py-0.5 rounded-md border border-[var(--border-color)]">
                      {count.toLocaleString()}
                    </span>
                  </div>
                ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function MetricCard({ icon, label, value }) {
  return (
    <div className="bg-[var(--bg-elevated)] border border-[var(--border-color)] rounded-xl p-4 flex flex-col justify-between h-28">
      <div className="flex justify-between items-start">
        <div className="p-2 bg-[var(--bg-base)] rounded-lg text-[var(--text-muted)]">
          {React.cloneElement(icon, { size: 16 })}
        </div>
      </div>
      <div>
        <div className="text-2xl font-bold text-white mb-1 font-mono tracking-tight">{value}</div>
        <div className="text-[10px] uppercase tracking-wider font-semibold text-[var(--text-muted)]">{label}</div>
      </div>
    </div>
  );
}

function DomainBar({ label, count, total, color }) {
  const percentage = total > 0 ? (count / total) * 100 : 0;
  return (
    <div>
      <div className="flex justify-between text-xs mb-1">
        <span className="text-[var(--text-secondary)] font-medium">{label}</span>
        <span className="text-[var(--text-muted)] font-mono">{count} files</span>
      </div>
      <div className="h-1.5 w-full bg-[var(--bg-base)] rounded-full overflow-hidden">
        <div className={`h-full ${color} rounded-full`} style={{ width: `${percentage}%` }} />
      </div>
    </div>
  );
}
